node {
   def commit_id
   stage('Preparation') {
      sh 'docker -v'
      checkout scm
      sh "git rev-parse --short HEAD > .git/commit-id"                        
      commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v2/', '35b6fda9-4ca4-4c7d-bd6f-8145f5d0d371	') {
       def app = docker.build("iamkhaledh/test-example-nodejs:${commit_id}", '.').push()
     }
   }
}
